[project]
name = "alice"

[model]
hugging_face_name = "databricks/dolly-v2-3b"

[prompt]
initializer = "Write an exerpt of a surreal children's fantasy story set in a subterranean world populated by peculiar anthropomorphic creatures. Go!\n\n"

[training]
block_size = 700
checkpoint_interval = 20
eval_interval = 5
eval_blocks = 8
batch_size = 1
base_acc_steps = 16
acc_doubling_rate = 0
plateau_steps = 0

[optimizer]
lr = 1e-2
beta1 = 0.0
decay_rate = -0.8
weight_decay = 0.1
scale_parameter = false
relative_step = false

[scheduler]
num_warmup_steps = 0
num_cycles = 8
num_training_steps = 100
