[project]
name = "george"

[data]
name = "unspoken-sermons"
url = "https://www.gutenberg.org/cache/epub/9057/pg9057.txt"

[model]
hugging_face_name = "databricks/dolly-v2-3b"

[prompt]
initializer = "Write an exerpt from George MacDonald's book, Unspoken Sermons. It's available on Project Gutenburg. Go!\n\n"

[training]
block_size = 2000
checkpoint_interval = 20
eval_interval = 5
eval_blocks = 1
batch_size = 1
base_acc_steps = 16
acc_doubling_rate = 0
plateau_steps = 0

[optimizer]
lr = 0.1
beta1 = 0.0
decay_rate = -0.8
weight_decay = 0.1
scale_parameter = false
relative_step = false

[scheduler]
num_warmup_steps = 10
num_cycles = 8
num_training_steps = 10000
